# Generated by Django 4.0.4 on 2022-05-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agenda_semanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('tipo_visita', models.CharField(choices=[('1', 'desparacitacion'), ('2', 'consulta veterinaria'), ('3', 'eutanasia')], max_length=1)),
                ('agenda_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muni_app.agenda_semanal')),
            ],
        ),
    ]
